Re: https://github.com/seren/freenas-temperature-graphing/issues/10
seren/freenas-temperature-graphing pull request #11
Opened 2017-08-11 03:33 UTC by hexadecagram

Modified data collection, graph generation, and format scripts to better accommodate non-S.M.A.R.T. drives, min and max safe temperature limits for mechanical drives, and a wider overall temperature range, and to produce accurate verbose output, and create graphs with more readable curves.

2017-08-15 18:00 UTC, seren requested changes

2017-08-15 18:00 UTC, seren commented on rrd-graph.sh
> +for i in $(/sbin/sysctl -n kern.disks | grep da); do
Since `/sbin/sysctl -n kern.disks` outputs on a single line, grep will match the entire line (provided it contains "da") and so will have no filtering effect. I think the awk is still necessary.

2017-08-15 18:00 UTC, seren commented on rrd-graph.sh
> +  DevTemp=$(/usr/local/sbin/smartctl -a /dev/"${i}" | awk '/Temperature_C/{print $10}');
Nice removal of the redundant awk. This over-matches on my system however:
```
$ /usr/local/sbin/smartctl -a /dev/ada0 | awk '/Temperature_C/{print $10}'
42
42
$ /usr/local/sbin/smartctl -a /dev/ada0 | grep Temperature_C
190 Airflow_Temperature_Cel 0x0022   058   050   045    Old_age   Always       -       42 (Min/Max 24/48)
194 Temperature_Celsius     0x0022   042   050   000    Old_age   Always       -       42 (0 15 0 0 0)
```
Cutting out just the `194` works though:
```
/usr/local/sbin/smartctl -a /dev/ada0 | awk '/ Temperature_Celsius/{print $10}'
42
```

2017-08-20 18:51 UTC, hexadecagram reviewed
Responded to comments. Additional changes will be in a follow-up commit.

2017-08-20 18:51 UTC, hexadecagram commented on rrd-graph.sh
> +for i in $(/sbin/sysctl -n kern.disks | grep da); do
Actually, all that is needed is the output of sysctl -n kern.disks with no modification. **Only** disk devices should be listed by that command, so there's no need to filter out non-**disk** devices (which is what the awk really accomplishes). FreeBSD names all drives /dev/ada* or /dev/da*. So, the sanity check to filter out non-S.M.A.R.T. drives that follows is really all we need.

It's probably worth mentioning that some USB drives will require a -d option to smartctl in order to display their variables. I have a WD My Book Duo attached to a Linux machine that does exactly this.

2017-08-20 18:51 UTC, hexadecagram commented on rrd-graph.sh
> +  DevTemp=$(/usr/local/sbin/smartctl -a /dev/"${i}" | awk '/Temperature_C/{print $10}');
Hmm. This is a tricky one. In my system, I have 2 drives. Each drive matches **either** attribute 190 **OR** attribute 194. I do not have any drives that have both. I think it would be wise to determine which of the two attributes is more relevant and figure out a way to match just one of them.

If I had to guess, it would be Temperature_Celsius, which presumably measures the **internal** temperature of the drive.

If we can agree about that, the question then becomes how do we handle the case when a drive **only** outputs attribute 190 and not 194?

2017-08-20 18:51 UTC, hexadecagram commented on rrd-graph.sh
> +  DevTemp=$(/usr/local/sbin/smartctl -a /dev/"${i}" | awk '/Temperature_C/{print $10}');
[Here's a list of S.M.A.R.T. attributes.](https://en.wikipedia.org/wiki/S.M.A.R.T.#Known_ATA_S.M.A.R.T._attributes) Looks like I was correct. It also looks like 190 and 194 are the **only** temperature-related attributes, so we're in luck there. I'll see if I can't bang out some code to handle this situation.

2017-08-20 18:51 UTC, hexadecagram commented on rrd-graph.sh
> +  DevTemp=$(/usr/local/sbin/smartctl -a /dev/"${i}" | awk '/Temperature_C/{print $10}');
I have written some code that I think addresses the issue. I let it run overnight and didn't see any problems on my end. Give it a spin and let me know if it works for you. I also took the opportunity to factor out rrd-lib.sh, which contains some redundant code as well as function definitions that would probably make maintaining this a little easer. There's probably more to do but I at least got the ball rolling for you.

2017-08-23 23:11 UTC, seren commented
Cool. Could you explain the awk code?
```
BEGIN         { attr=0; temp=0 }
$1 ~ /19[04]/ { if (attr != "194") { attr=$1; temp=$10 } }
END           { print temp }
```
It looks like it operates on lines beginning with 190 or 194, but I'm not sure what the conditional is doing.

2017-08-23 23:45 UTC, hexadecagram commented
It's a tricky bit of code and yeah it's not completely obvious as to how it works. You could massage the following into a comment before you commit if you like.

You're correct. The second line of the AWK program matches the first field if it is 190 or 194. We have to consider 5 cases with the program:

1. The device neither reports attribute 190 nor 194, which results in the whole AWK script matching nothing with the result of DevTemp being set to '' (sanity check failed, so nothing is graphed for this device).
2. The device only reports attribute 190. The temp variable is initialized to 0 so it gets set and attr is set to 190.
3. The device only reports attribute 194. The temp variable is initialized to 0 so it gets set and attr is set to 194.
4. The device reports attribute 190 before 194. The temp variable is initialized to 0 so on the first match it gets set and attr is set to 190. On the second match, $1 is 194 so temp is not overwritten and attr remains set to 190, so the temperature reported by attribute 190 is given preference.
5. The device reports attribute 194 before 190. The temp variable is initialized to 0 so on the first match it gets set and attr is set to 194. On the second match, $1 is 190 so temp gets overwritten and attr is set to 190, so once again the temperature reported by attribute 190 is given preference.

2017-08-23 23:56 UTC, seren commented
Ahh, ok. So it's setting the temperature from matching lines, giving precedence to attribute 190. When I tried it, it output a temperature of zero for my usb non-SMART drive. I think that if it doesn't find a match, the output is the default value of `temp` which is 0. I tried setting it -99 (which should never be a valid temperature) and catching that in the loop which worked, but I'm not sure if you can think of a better method:

```
BEGIN         { attr=0; temp=-99 }
$1 ~ /19[04]/ { if (attr != "194") { attr=$1; temp=$10 } }
END           { print temp }
```
```
    if ! [ "$DevTemp" == "-99" ]; then
      drivedevs="${drivedevs} ${i}"
      [ -n "$verbose" ] && echo "drivedevs: ${drivedevs}"
    fi
```

2017-08-23 23:58 UTC, hexadecagram commented
I edited my comment with a solution because I thought of exactly that. ;-)

2017-08-24 02:07 UTC, hexadecagram commented
I edited my comment with a solution because I thought of exactly that after the fact. ;-)

Note that I also changed the END block rather than modify the outer bash script, as you did. Would work either way, but IMO having it in the AWK program makes it cleaner and more obvious without having to explain it in a comment.

2017-08-24 04:56 UTC, seren commented
Cool, I agree that having it in the awk script is cleaner. I'll merge this and add the change. I'll probably stick with the -99 rather than -273.15 since it's a bit easier to read/understand and I can't imagine any FreeNAS server drive being either temperature while being turned on. :)

2017-08-24 04:56 UTC, merged

2017-08-24 06:52 UTC, hexadecagram commented
That's probably me just letting my FreeBSD side show through. **Very** scientifically-minded bunch. But you're right, it's not likely that they use FreeNAS on the space shuttle. And even if they did, hey, it's open source.